services:
  rabbitmq:
    restart: no
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    restart: no
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  reddit-api:
    restart: no
    build:
      context: ./src/reddit-api
      dockerfile: Dockerfile
    container_name: reddit-api
    ports:
      - "3001:3001"
    command: node app.js
    depends_on:
      - redis

networks:
  default:
    name: pizzanet

volumes:
  redis-data:
  rabbitmq-data:
