services:
  rabbitmq:
    restart: no
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    restart: no
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  nodejs:
    restart: no
    image: node:18
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reddit-api
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    command: node /app/src/Server/app.js
    depends_on:
      - redis

  # not working on apple silicon right now
  # redis-ui:
  #   image: rediscommander/redis-commander:latest
  #   restart: always
  #   container_name: redis-ui
  #   environment:
  #     - REDIS_HOSTS=redis:6379
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - redis

networks:
  default:
    name: pizzanet

volumes:
  redis-data:
  rabbitmq-data:
